const defaultFilters = [
	"*://*.doubleclick.net/*",
	"*://partner.googleadservices.com/*",
	"*://*.googlesyndication.com/*",
	"*://*.google-analytics.com/*",
	"*://creative.ak.fbcdn.net/*",
	"*://*.adbrite.com/*",
	"*://*.exponential.com/*",
	"*://*.quantserve.com/*",
	"*://*.scorecardresearch.com/*",
	"*://*.zedo.com/*",
	"*://*.flipkart.com/*",
    "*://*.amazon.in/*",
    "*://*.snapdeal.com/*",
    "*://*.paytm.com/*",
    "*://*.olx.in/*",
    "*://*.quikr.com/*",
    "*://*.jio.com/*",
    "*://*.bollywoodlife.com/*",
    "*://*.pinkvilla.com/*",
    "*://*.scroll.in/*",
    "*://*.etfreak.com/*",
    "*://*.investopedia.com/*",
    "*://*.sunpharma.com/*",
	"*://*.vimalgutkha.com/*",
	"*://*.jkcement.com/*"	,
	"*://*.ultratechcement.com/*",
    "*://*.fortuneindia.com/*",
    "*://*.yourstory.com/*",
    "*://*.gadgetsnow.com/*",
    "*://*.gizmochina.com/*",
    "*://*.xda-developers.com/*",
    "*://*.xda-forums.com/*",
    "*://*.xda-labs.com/*",
    "*://*.xda-board.com/*",
    "*://*.xda-portal.com/*",
    "*://*.xda-legacy.com/*",
    "*://*.xda-forum.com/*",
    "*://*.xda-forums.org/*",
    "*://*.xda-developers.com/*",
    "*://*.xda-forums.net/*",
    "*://*.xda-forum.org/*",
    "*://*.xda-forums.com/*",
	"*://*.adbrite.com/*",
	"*://*.exponential.com/*",
	"*://*.quantserve.com/*",
	"*://*.scorecardresearch.com/*",
	"*://*.zedo.com/*",
]

chrome.webRequest.onBeforeRequest.addListener(
    function(details) { return { cancel: true }},
    { urls: defaultFilters },
    ["blocking"]
)

